name: CI
on: push

jobs:

  integration:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.10'

      - name: Test gosu with Golang
        run: |
          ./build.sh
          gosu root ./script/install-runc
