name: CI

on:
  pull_request:
  push:

defaults:
  run:
    shell: 'bash -Eeuo pipefail -x {0}'

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: ./build.sh
      - run: ./test.sh gosu-amd64
      - run: ./test.sh gosu-i386
      - run: ./test.sh --debian gosu-amd64
      - run: ./test.sh --debian gosu-i386
