name: CI
on: push

jobs:

  integration:
    name: Test
    runs-on: ubuntu-18.04

    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.10'

      - name: Set env
        shell: bash
        run: |
          echo "::set-env name=GOPATH::${{ github.workspace }}"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: src/github.com/fahedouch/gosu

      - name: Test gosu with Golang
        run: |
          echo $(id -u)
          whoami
          ./build.sh
          chmod +s gosu-$(dpkg --print-architecture)
          ./gosu-$(dpkg --print-architecture) root script/install-runc
          ls ${{ github.workspace }}/src/github.com
        working-directory: src/github.com/fahedouch/gosu